'use strict';

angular.module("basic").config(["$translateProvider", function($translateProvider) {
  $translateProvider.translations("en", {
    ADD_NEW_TABLE: "Add new table",
    ADD_NEW_SCHEMA: "Add New Schema",
    EDIT_SCHEMA: "Edit Schema",
    NAME: "Name",
    INDEX_TYPE: "Index Type",
    ROWKEY_EXPRESSION: "Rowkey Expression",
    TABLE_EXPRESSION: "Table Expression",
    SCHEMA: "Schema",
    SCHEMA_NAME: "Schema Name",
    WEIGHT: "Weight",
    FIELDS: "Fields",
    TABLE: "Table",
    SEARCH: "Search",
    REGION_NUM: "Region Number",
    REGION_SPLIT: "Region Split",
    SOLR_SHARDS: "Solr Shards",
    SOLR_REPLICAS: "Solr Replicas",
    OK: "OK",
    CANCEL: "Cancel",
    NEXT: "Next",
    ERROR: "Error",
    PREV: "Previous",
    EDIT_TABLE_FIELDS: "Edit Table Fields",
    FIELD_NAME: "Field Name:",
    STORE_TYPE: "Store Type:",
    CONTENT_FIELD: "Content Field",
    INNER_FIELD: "Inner Field",
    FIELD_INDEX: "Field Index",
    INDEXED: "Indexed",
    QUERY_FIELD: "Query Field",
    ID_FORMATTER: "ID Formatter",
    INTABLE_NAME: "name",
    INTABLE_TYPE: "type",
    INTABLE_SEPARATOR: "separator",
    INTABLE_STORE_TYPE: "store type",
    INTABLE_INDEX_TYPE: "index type",
    INTABLE_INNER_FIELD: "inner field",
    INTABLE_CONTENT_FIELD: "content field",
    INTABLE_QUERY_WEIGHT: "query weight",
    INTABLE_OPERATION: "operation",
    INTABLE_WEIGHT: "weight",
    INTABLE_DISPLAY: "display in search",
    DISPLAY: "display",
    SELECT_TYPE: "Select Type",
    SELECT_SCHEMA: "Select schema",
    SELECT_INDEX_TYPE: "Select index type",
    SELECT_FIELD_STORE_TYPE: "Select field store type",
    SELECT_FIELD_INDEX_TYPE: "Select field index type",
    SELECT_FIELD_CONTENT_FIELD: "Select existed content field",
    SELECT_FIELD_INNER_FIELD: "Select existed inner field",
    SELECT_QUERY_FIELD: "Select existed field to query",
    BASIC_INFO: "Basic Info",
    ADD: "Add",
    EDIT: "Edit",
    DELETE: "Delete",
    UNAVAILABLE: "Unavailable",
    YES: "Yes",
    NO: "No",
    CONFIRMATION: "Confirmation",
    WARNING: "Warning",
    MODALMSG_FILL_IN_ALL: "Please fill in all inputs marked as *",
    MODALMSG_NO_FIELDS: "No fields of schema defined!",
    MODALMSG_QUERY_FIELD_TIP: "Tips: Content fields or Fields typed as 'text*' can be configured as query fields",
    CONFIRM_ADD_TABLE: "Create table now?",
    CONFIRM_EDIT_TABLE: "Change the schema of table now?",
    CONFIRM_DELETE_TABLE: "Want to delete the table selected? All data related will be lost!",
    CONFIRM_DELETE_SCHEMA: "Are you sure to delete the schema selected?",
    CONFIRM_ADD_SCHEMA: "Create schema now?",
    CONFIRM_EDIT_SCHEMA: "Recreate schema now?",
    CONFIRM_DELETE_SCHEMA_ERR: "There are tables belong to the schema. Delete all related tables first of all!",
    CONFIRM_EDIT_SCHEMA_ERR: 'There are tables belong to the schema. You can just edit fields of schema in "Table" panel.',
    CONFIRM_TITLE_CREATE_TABLE_ERROR: "Error occur during creation of table",
    CONFIRM_TITLE_EDIT_TABLE_ERROR: "Error occur during editing table",
    CONFIRM_TITLE_CREATE_SCHEMA_ERROR: "Error occur during creation of schema",
    EMPTY: "(empty)",
    UNDEFINED: "(undefined)",
    NULL: "(null)",
    HELP_EXPRESSION_TITLE: "Help to build an expression",
    HELP_EXPRESSION_CONTENT: "Want to learn",
    HELP_EXPRESSION_LINK: "more",
    ROWS: "Rows",
    CONDITIONS: "Conditions",
    ADVANCE_SEARCH: "Advance Search",
    WITH_HBASE: "With Hbase",
    HBASE: "Hbase",
    HBASE_FAMILY: "family",
    HBASE_COLUMN: "column",
  });
}]);